"""Positive smoke — list Directory groups and write them to a file.

Uses GOOGLE_GROUP_DOMAIN_NAME (testenv.example in this env). Do not append
@example.com here; that domain is for a later org/SA via the same env var.

Control 3 against the live Directory list is optional (APP_SMOKE_RUN_CONTROL_3).
"""

import logging
import os

import yaml

from audit_tool.framework.gcp_client import GcpPolicyClient, resolve_credentials_identity
from audit_tool.framework.paths import DIRECTORY_GROUPS_LISTED
from audit_tool.framework.runtime import (
    get_required_env,
    validate_auth_runtime,
)
from audit_controls.control_3 import run as run_control_3

_SENSITIVE_ENV = frozenset(
    {
        "VAULTED_GCP_SERVICE_ACCOUNT",
        "VAULT_ROLE_ID",
        "VAULT_SECRET_ID",
    }
)


def _truthy(name: str, default: str = "true") -> bool:
    return os.environ.get(name, default).strip().lower() not in ("0", "false", "no")


def _smoke_check_gcp_apis(client: GcpPolicyClient) -> None:
    """Prove the SA works on GCP APIs its IAM role already grants."""
    checks = client.check_gcp_api_access()
    failed = [check for check in checks if not check["ok"]]
    if failed:
        raise RuntimeError(
            "GCP API access check failed for "
            + ", ".join(check["permission"] for check in failed)
            + ". The credential itself is not usable, so fix this before "
            "looking at Directory access."
        )


def _smoke_write_groups_file(groups: list) -> str:
    """Write Directory emails as returned. Does not rewrite the domain."""
    path = os.environ.get("APP_SMOKE_GROUPS_OUTPUT", "").strip() or str(
        DIRECTORY_GROUPS_LISTED
    )
    payload = {
        "domain": os.environ.get("GOOGLE_GROUP_DOMAIN_NAME", "").lower(),
        "count": len(groups),
        "groups": groups,
    }
    parent = os.path.dirname(path)
    if parent:
        os.makedirs(parent, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(
            "# Generated by smoke Directory groups.list. Do not edit.\n"
            "# Emails are as returned by Directory — domain is not rewritten.\n"
        )
        yaml.safe_dump(payload, handle, sort_keys=False, allow_unicode=True)
    logging.info("Wrote %d group(s) to %s", len(groups), path)
    return path


def _smoke_list_directory_groups(client: GcpPolicyClient) -> list:
    """Paginate Admin Directory groups.list for GOOGLE_GROUP_DOMAIN_NAME."""
    sample_n = int(os.environ.get("APP_SMOKE_GROUP_SAMPLE", "20"))
    groups = client.list_all_directory_groups()
    logging.info("Smoke Directory list: %d group(s) total", len(groups))
    for item in groups[:sample_n]:
        logging.info(
            "  group: %s (%s)",
            item.get("email") or "(no email)",
            item.get("name") or "",
        )
    if len(groups) > sample_n:
        logging.info(
            "  … and %d more (set APP_SMOKE_GROUP_SAMPLE to show more)",
            len(groups) - sample_n,
        )
    if not groups:
        raise RuntimeError(
            "Directory groups.list returned 0 groups. "
            "Check GOOGLE_GROUP_DOMAIN_NAME and that the SA has Directory Groups read."
        )
    return groups


def run() -> int:
    logging.info("=== Smoke test start (positive) ===")

    logging.info("Smoke step 1/4: runtime environment")
    required = get_required_env()
    missing = [name for name in required if not os.environ.get(name)]
    if missing:
        raise ValueError(f"Missing env: {', '.join(missing)}")
    for name in required:
        if name in _SENSITIVE_ENV:
            logging.info("  %s: set", name)
        else:
            logging.info("  %s: %s", name, os.environ.get(name))
    logging.info(
        "  GOOGLE_GROUP_DOMAIN_NAME: %s",
        os.environ.get("GOOGLE_GROUP_DOMAIN_NAME"),
    )
    if os.environ.get("GOOGLE_CUSTOMER_ID"):
        logging.info("  GOOGLE_CUSTOMER_ID: %s (fallback only; list uses domain)", os.environ["GOOGLE_CUSTOMER_ID"])
    if os.environ.get("CERT_FILE"):
        logging.info("  CERT_FILE: %s", os.environ["CERT_FILE"])
    validate_auth_runtime()
    if not os.environ.get("GOOGLE_GROUP_DOMAIN_NAME"):
        raise ValueError("Missing env: GOOGLE_GROUP_DOMAIN_NAME")
    logging.info("Smoke step 1/4 ok")

    creds_mode = os.environ.get("SOURCE_CREDENTIALS_GCP", "VAULT")
    logging.info("Smoke step 2/4: %s credentials + GCP API access", creds_mode)
    client = GcpPolicyClient(load_policies=False)
    identity = resolve_credentials_identity(client.credentials)
    logging.info("  running as: %s", identity)
    _smoke_check_gcp_apis(client)
    logging.info("Smoke step 2/4 ok")

    logging.info("Smoke step 3/4: Directory groups.list")
    if not _truthy("APP_SMOKE_LIST_GROUPS"):
        raise RuntimeError(
            "APP_SMOKE_LIST_GROUPS is off; smoke must list groups. "
            "Export APP_SMOKE_LIST_GROUPS=true."
        )
    groups = _smoke_list_directory_groups(client)
    logging.info("Smoke step 3/4 ok")

    logging.info("Smoke step 4/4: write listed groups file")
    output_path = _smoke_write_groups_file(groups)
    logging.info("Smoke step 4/4 ok: %s", output_path)

    if _truthy("APP_SMOKE_RUN_CONTROL_3", default="false"):
        logging.info("Smoke extra: Control 3 (live Directory pairs)")
        result = run_control_3()
        logging.info("=== Smoke test finished exit=%s (ran as %s) ===", result, identity)
        return result

    logging.info("=== Smoke test finished exit=0 (ran as %s) ===", identity)
    return 0
