"""Paths to static control data files under src/controls_data/."""

import os
from pathlib import Path

# framework/paths.py → src/
SRC_DIR = Path(__file__).resolve().parents[2]
DATA_DIR = SRC_DIR / "controls_data"

# Vault TLS CA chain PEM (paste contents locally; CERT_FILE may be bare filename).
INTERNAL_CA_CHAIN_UAT = SRC_DIR / "InternalCAChain_UAT.pem"
DEPLOY_INTERNAL_CA_CHAIN_UAT = "/apps/InternalCAChain_UAT.pem"

CONTROL_1_RO_POLICY = DATA_DIR / "testenv_control_1_ro_policy.yaml"
CONTROL_1_PERMISSIONS = DATA_DIR / "testenv_control_1_permissions.json"
CONTROL_1_ALLOWLIST = DATA_DIR / "testenv_control_1_allowlist.yaml"
CONTROL_5_SA_POLICY = DATA_DIR / "testenv_control_5_sa_policy.yaml"
CONTROL_5_ALLOWLIST = DATA_DIR / "testenv_control_5_allowlist.yaml"
# Written by smoke / control_2 / control_3 after Directory groups.list (gitignored).
DIRECTORY_GROUPS_LISTED = DATA_DIR / "testenv_directory_groups_listed.yaml"
# Generated by control_2 / control_3 from the live Directory list (gitignored).
CONTROL_2_GROUPS_REALTIME = DATA_DIR / "testenv_control_2_groups_realtime.yaml"
CONTROL_3_GROUPS_REALTIME = DATA_DIR / "testenv_control_3_groups_realtime.yaml"
# Generated by control_1 from live Asset IAM scan of RO groups (gitignored).
CONTROL_1_FINDINGS_REALTIME = DATA_DIR / "testenv_control_1_findings_realtime.yaml"
# Generated by control_5 from live Asset SA + IAM scan (gitignored).
CONTROL_5_FINDINGS_REALTIME = DATA_DIR / "testenv_control_5_findings_realtime.yaml"


def resolve_cert_file(cert_file: str = "") -> str:
    """Resolve CERT_FILE to an absolute path (cwd, then src/, then /apps/)."""
    raw = (cert_file or os.environ.get("CERT_FILE", "")).strip()
    if not raw:
        raw = "InternalCAChain_UAT.pem"
    path = Path(raw)
    if path.is_file():
        return str(path.resolve())
    if not path.is_absolute():
        for candidate in (
            SRC_DIR / raw,
            Path(DEPLOY_INTERNAL_CA_CHAIN_UAT),
            INTERNAL_CA_CHAIN_UAT,
        ):
            if candidate.is_file():
                return str(candidate.resolve())
    return str(path)


# OpenShift: WORKDIR /apps, COPY src/ .
DEPLOY_CONTROL_1_RO_POLICY = "/apps/controls_data/testenv_control_1_ro_policy.yaml"
DEPLOY_CONTROL_1_PERMISSIONS = (
    "/apps/controls_data/testenv_control_1_permissions.json"
)
DEPLOY_CONTROL_1_ALLOWLIST = "/apps/controls_data/testenv_control_1_allowlist.yaml"
DEPLOY_CONTROL_5_SA_POLICY = "/apps/controls_data/testenv_control_5_sa_policy.yaml"
DEPLOY_CONTROL_5_ALLOWLIST = "/apps/controls_data/testenv_control_5_allowlist.yaml"
